name: 'Sync'
on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches:
      - master

jobs:
  sync:
    name: Sync user agent
    runs-on: [ubuntu-latest]
    env:
      DOCKER_BUILDKIT: 1
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install deps
      run: |
        apt-get install -y libxss1 libappindicator1 libindicator7
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        apt install -y ./google-chrome*.deb
    - name: Sync
      run: |
        ./sync.sh
