name: 'Sync'
on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches:
      - master

jobs:
  sync:
    name: Sync user agent
    runs-on: [ubuntu-latest]
    env:
      DOCKER_BUILDKIT: 1
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install deps
      run: |
        sudo apt-get install -y chromium-chromedriver
        sudo apt-get install -y python3-selenium
    - name: Sync
      run: |
        ./sync.sh
